### PR TITLE
Add 2D support for Cellpose & napari workflows task (closes #398)

### LINKED ISSUE #398: Support 2D-only OME-Zarrs?
We save our 2D OME-Zarrs as (z, y, x) images with (1, size_y, size_x). Some other OME-Zarrs (e.g. the ones generated by the faim-hcs OME-Zarr converter) can be (x,y) only, i.e. (size_y, size_x). 

This then leads to issues in our processing, for example the following error in cellpose. The problem here is a mismatch between ROI dimensions (ROIs always being z, y, x) and image dimensions. 

```
2023-06-07 13:03:23,100; INFO; START cellpose_segmentation task
2023-06-07 13:03:23,100; INFO; zarrurl='/Users/joel/Desktop/20230607_MD_Maurice_test2/Plate.zarr/C/3/0'
2023-06-07 13:03:23,217; INFO; data_zyx.shape=(3072, 3072)
2023-06-07 13:03:23,242; INFO; ROI table at /Users/joel/Desktop/20230607_MD_Maurice_test2/Plate.zarr/C/3/0/tables/well_ROI_table has attrs: <zarr.attrs.Attributes object at 0x29e828580>
2023-06-07 13:03:23,242; INFO; ROI table at /Users/joel/Desktop/20230607_MD_Maurice_test2/Plate.zarr/C/3/0/tables/well_ROI_table cannot be used for masked loading. Set use_masks=False.
2023-06-07 13:03:23,242; INFO; use_masks=False
2023-06-07 13:03:23,242; INFO; reset_origin=True
2023-06-07 13:03:23,243; INFO; pxl_zyx=[1.0, 0.6834, 0.6834]
2023-06-07 13:03:23,243; INFO; new_labels=['organoids']
2023-06-07 13:03:23,243; INFO; existing_labels=[]
2023-06-07 13:03:23,251; INFO; Output label path: /Users/joel/Desktop/20230607_MD_Maurice_test2/Plate.zarr/C/3/0/labels/organoids/0
2023-06-07 13:03:23,261; INFO; mask will have shape (3072, 3072) and chunks ((2048, 1024), (2048, 1024))
2023-06-07 13:03:23,263; INFO; TORCH CUDA version not installed/working.
2023-06-07 13:03:23,265; INFO; >> cyto2 << model set to be used
2023-06-07 13:03:23,265; INFO; >>>> using CPU
2023-06-07 13:03:23,265; INFO; WARNING: MKL version on torch not working/installed - CPU version will be slightly slower.
2023-06-07 13:03:23,265; INFO; see https://pytorch.org/docs/stable/backends.html?highlight=mkl
2023-06-07 13:03:23,369; INFO; >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2023-06-07 13:03:23,369; INFO; Start cellpose_segmentation task for /Users/joel/Desktop/20230607_MD_Maurice_test2/Plate.zarr/C/3/0
2023-06-07 13:03:23,369; INFO; relabeling: True
2023-06-07 13:03:23,369; INFO; do_3D: True
2023-06-07 13:03:23,369; INFO; use_gpu: False
2023-06-07 13:03:23,369; INFO; level: 1
2023-06-07 13:03:23,369; INFO; model_type: cyto2
2023-06-07 13:03:23,369; INFO; pretrained_model: None
2023-06-07 13:03:23,369; INFO; anisotropy: 1.4632718759145449
2023-06-07 13:03:23,369; INFO; Total well shape/chunks:
2023-06-07 13:03:23,369; INFO; (3072, 3072)
2023-06-07 13:03:23,369; INFO; ((2048, 1024), (2048, 1024))
2023-06-07 13:03:23,369; INFO; Now starting loop over 1 ROIs
2023-06-07 13:03:23,369; INFO; Now processing ROI 1/1
Traceback (most recent call last):
  File "/Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.9.4/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 699, in <module>
    run_fractal_task(
  File "/Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.9.4/venv/lib/python3.9/site-packages/fractal_tasks_core/_utils.py", line 91, in run_fractal_task
    metadata_update = task_function(**task_args.dict(exclude_unset=True))
  File "/Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.9.4/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 516, in cellpose_segmentation
    img_np = np.expand_dims(data_zyx[region].compute(), axis=0)
  File "/Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.9.4/venv/lib/python3.9/site-packages/dask/array/core.py", line 1978, in __getitem__
    index2 = normalize_index(index, self.shape)
  File "/Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.9.4/venv/lib/python3.9/site-packages/dask/array/slicing.py", line 904, in normalize_index
    raise IndexError("Too many indices for array")
IndexError: Too many indices for array
```

TODO: Figure out whether we can support 2D OME-Zarr images
1) by adapting the loading to support that?
2) by adapting our ROI tables for 2D images?

I'd prefer 1, but need to evaluate

### PR DESCRIPTION
**Pull request by jluethi**
Adding support to process 2D OME-Zarr files with the Cellpose & napari workflows task.

The resulting label images by cellpose are always 3D arrays. If the input image was 2 dimensional, it's of shape (1, shape_y, shape_x).

What still needs to be done:
- [x] Check whether any tests fail
- [x] Add tests for new lib function
- [x] Test napari workflows further: I covered some scenarios, but I'm not sure whether the "calculate a label image in napari workflows based on an actual 2D image OME-Zarr intensity image" would work as expected. I think it should (and should just be saved as an actual 2D image), but to be tested a bit further.
- [x] Plus test the different interactions with `expected_dimensions` and if there are weird edge cases there

I want to cover 1 & 2 for this PR. Point 3 may be moved to another issue => https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/411

### CODE REVIEW

**Comment by jluethi** [comment]
@tcompa This would PR be ready for a review if you have time for one. Some work is postponed to https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/411 to get the core functionality already in now.

**Comment by jluethi** [comment]
Now added a workaround to handle coordinateTransformations that follow the spec better than us, see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/420#issuecomment-1584625661

**Comment by tcompa** [comment]
With b310ce5, I added some more explicit constraints (notably the fact that we rely on `region` always having three elements).

**Comment by tcompa** [comment]
For the record, the `load_region` block
```python
        img = data_zyx[(region[1], region[2])]
        if return_as_3D:
            img = np.expand_dims(img, axis=0)
```
produces a dask array even when `return_as_3D=True` (which was not obvious to me at a first look):

```
    img: dask.array<getitem, shape=(1, 1), dtype=float64, chunksize=(1, 1), chunktype=numpy.ndarray> (Array) len=1

    img: dask.array<reshape, shape=(1, 1, 1), dtype=float64, chunksize=(1, 1, 1), chunktype=numpy.ndarray> (Array) len=1
```

**Comment by jluethi** [comment]
> produces a dask array even when return_as_3D=True (which was not obvious to me at a first look):

The idea was to separate the optional dimension expansion (return_as_3D) from the compute. If we have ideas for better variable names for them, we can of course adapt that API :)

**Comment by tcompa** [comment]
> The idea was to separate the optional dimension expansion (return_as_3D) from the compute. If we have ideas for better variable names for them, we can of course adapt that API :)

Nothing wrong with the way it's written. I just didn't know/remember that a numpy function applied to a dask array returns a dask array.

**Comment by tcompa** [comment]
>  Plus test the different interactions with expected_dimensions and if there are weird edge cases there

If you run a `napari_workflows_wrapper` with `expected_dimension=3` and a CYX input, you will get
```python
ValueError('Something wrong: label_shape=(540, 1280) but expected_dimensions=3')
```
(as verified with the new [test_napari_workflow_CYX_wrong_dimensions](https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/403/commits/905af2709770d28aca4242ce01845ae6e02ab65e) test).

Are there other useful checks that come to mind?

**Comment by jluethi** [comment]
> Are there other useful checks that come to mind?

Should we include a test that a 3D input with the z dimension > 1 fails when we set `expected_dimension=2`?

Let's not go too deep here though. I thin when doing the axes refactor, we may want to reconsider whether expected_dimensions is a parameter that really needs to be exposed to the user

**Comment by tcompa** [comment]
> Should we include a test that a 3D input with the z dimension > 1 fails when we set `expected_dimension=2`?

We already had the following
```python
cases = [
    (2, 2, True),
    (2, 3, False),
    (3, 3, True),
    (3, 2, True),
]


@pytest.mark.parametrize(
    "expected_dimensions,zarr_dimensions,expected_success", cases
)
def test_expected_dimensions(
    expected_dimensions: int,
    zarr_dimensions: int,
    expected_success: bool,
    tmp_path: Path,
    testdata_path: Path,
    zenodo_zarr: List[str],
    zenodo_zarr_metadata: List[Dict[str, Any]],
):

    # Prepare zarr
    zarr_path = tmp_path / "tmp_out/"
    if zarr_dimensions == 2:
        metadata = prepare_2D_zarr(
            str(zarr_path),
            zenodo_zarr,
            zenodo_zarr_metadata,
            remove_labels=True,
        )
    else:
        metadata = prepare_3D_zarr(
            str(zarr_path), zenodo_zarr, zenodo_zarr_metadata
        )
    debug(zarr_path)
    debug(metadata)

    # First napari-workflows task (labeling)
    workflow_file = str(
        testdata_path / "napari_workflows/wf_5-labeling_only.yaml"
    )
    input_specs: Dict[str, Dict[str, Union[str, int]]] = {
        "input_image": {"type": "image", "wavelength_id": "A01_C01"},
    }
    output_specs: Dict[str, Dict[str, Union[str, int]]] = {
        "output_label": {
            "type": "label",
            "label_name": "label_DAPI",
        },
    }

    for component in metadata["image"]:
        arguments = dict(
            input_paths=[str(zarr_path)],
            output_path=str(zarr_path),
            metadata=metadata,
            component=component,
            input_specs=input_specs,
            output_specs=output_specs,
            workflow_file=workflow_file,
            input_ROI_table="FOV_ROI_table",
            level=3,
            expected_dimensions=expected_dimensions,
        )
        if expected_success:
            napari_workflows_wrapper(**arguments)
        else:
            with pytest.raises(ValueError):
                napari_workflows_wrapper(**arguments)
```
which I can tweak to also include the CYX case.

**Comment by tcompa** [comment]
> which I can tweak to also include the CYX case.

Done now (461c5de), with this list of cases
| zarr_dimensions 	| axes 	| expected_dimensions 	| expected_success 	|
|:---:	|:---:	|:---:	|:---:	|
| 2 	| CYX 	| 2 	| success 	|
| 2 	| CYX 	| 3 	| fail 	|
| 2 	| CZYX 	| 2 	| success 	|
| 2 	| CZYX 	| 3 	| success 	|
| 3 	| CZYX	| 2 	| fail 	|
| 3 	| CZYX 	| 3 	| success 	|

**Review by tcompa — APPROVED** [review]

**Pull request merged**
