### PR TITLE
Store `docs_info` and `docs_link` in the manifest

### LINKED ISSUE #405: Store main docstrings in the manifest
Refs
* https://github.com/fractal-analytics-platform/fractal-common/issues/90
* https://github.com/fractal-analytics-platform/fractal-server/issues/549
* https://github.com/fractal-analytics-platform/fractal/issues/531

### PR DESCRIPTION
**Pull request by ychiucco**
closes #405

### CODE REVIEW

**Comment by tcompa** [comment]
A couple of minor fixes are needed:
- [ ] The two new attributes should belong to each task item, and not to their `args_schema` field. That is, they should be moved one level up.
- [ ] Maybe we can get ast to work with short/long descriptions? Otherwise let's at least generalize the `split("Args")` statement to also include `"Arguments"`.

**Comment by tcompa** [comment]
Side-note for those who may be using the dev tools from fractal-tasks-core for other packages (@jluethi).

As of this PR (and subsequent releases), two scripts are renamed:
```
fractal_tasks_core/dev/check_args_schemas.py → fractal_tasks_core/dev/check_manifest.py
fractal_tasks_core/dev/new_args_schema.py → fractal_tasks_core/dev/update_manifest.py
```
This is because they now also include the handling of `docs_info` and `docs_link` attributes of manifest tasks.

I guess that usage of dev tools in other packages was rather based on lower-level functions, and not on these scripts, but here's a warning anyway.

Also note that these two `docs_info` and `docs_link` attributes are not (yet) implemented in a very general fashion, but rather customized for fractal-tasks-core. I'll gladly make these tools more flexible as soon as there is another instance where they would be useful/needed.

**Comment by tcompa** [comment]
This is in principle ready on my side - it'd be good if @mfranzon or @ychiucco can double check it.

**Comment by jluethi** [comment]
Ah, that's super cool to see! And the renaming makes sense.

I used a copy of the new_args_schema in fractal-faim-hcs here: https://github.com/jluethi/fractal-faim-hcs/blob/main/src/fractal_faim_hcs/dev/new_args_schema.py

Same for scmultiplex: https://github.com/fmi-basel/gliberal-scMultipleX/blob/main/src/scmultiplex/fractal/new_args_schema.py

Would be great if I can adapt those scripts to also generate the doc_info & doc_link! I'm fine with hard-coding a link. For those packages, even if we just point to the repository for each from each task, that's still fine. So that I could just hard-code. And `create_docs_info` looks like it may generalize, no?

**Comment by tcompa** [comment]
> Would be great if I can adapt those scripts to also generate the doc_info & doc_link! I'm fine with hard-coding a link. For those packages, even if we just point to the repository for each from each task, that's still fine. So that I could just hard-code. And create_docs_info looks like it may generalize, no?

I've tried to make the two update/check scripts even a bit more general.
Now there is a variable
```python
PACKAGE = "fractal_tasks_core"
```
at the beginning of the script, and in principle setting that one should be enough.
The only other customization is quite simple, and it consists in replacing the `create_docs_link()` function call with an hard-coded link (e.g. in `update_manifest.py`).

Warning: I've not (yet) tested the latest version on either scmultiplex of fractal-faim-hcs.

**Comment by jluethi** [comment]
That's great. I'll then test that on those two packages later and would open new issues if changes are required

**Comment by tcompa** [comment]
- [ ] Avoid relative imports in dev tools (came up while testing on scmultiplex)

**Comment by tcompa** [comment]
Tested on fractal-faim-hcs, and it also seems to work as expected. Both here and for scmultiplex I simply used the `update_manifest.py` script, with two updates:
* Change the value of the `PACKAGE` variable
* Replaced `create_docs_link(executable)` with some hard-coded link.

**Comment by tcompa** [comment]
> The only glitch I found is that the short description of a task function is meant to really be short (i.e. one line), otherwise docstring_parser considers the first line as a short description and the second line as a long description. Maybe I can find a workaround (but anyway it's a minor issue, for now).

This should be covered with [bd0cb3c](https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/486/commits/bd0cb3c7e8e8ba13b5960e97ffb81b591270e9f6), and even if it's not I guess it's a very minor glitch that we can solve later on.

Thus I'd say this is ready to merge.

**Pull request merged**
