### PR TITLE
253 Tests & fixes for metadata tables for parsing

### PR DESCRIPTION
**Pull request by jluethi**

### CODE REVIEW

**Comment by jluethi** [comment]
Closes #254 with https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/258/commits/20891e92a998f142481c92519d65e48cda497954

**Comment by jluethi** [comment]
Closes https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/257 with https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/258/commits/85d287e37820e76a907dd74111f15ec7a2cce52b

**Comment by jluethi** [comment]
Closing https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/253 via https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/258/commits/16d2f5ed377f399d2b6b488e92a8497f52c0e723 & https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/258/commits/7815fd404ce58e7d2d38612cee84e0b9343a2777

**Comment by jluethi** [comment]
@tcompa Once you're back, could you review this PR? Will be required to make the multiplexing parsing work because of the type checking bug in #257 (I'm working around it manually at the moment and it's working well)
Also, regarding the tests for the workflows: Maybe that can be parametrized? Not sure how to do that though in this setup and now at least we have tests for workflows based on table input as well :)

**Comment by tcompa** [comment]
> @tcompa Once you're back, could you review this PR?

It looks good, thanks. I added very minor changes here and there, but it's ready (I'll merge&release as soon as github CI is over).

> Also, regarding the tests for the workflows: Maybe that can be parametrized?

I've done it for the two ome-zarr-creation+yokogawa_parsing tests.

**Review by tcompa — APPROVED** [review]

**Pull request merged**
