### PR TITLE
Do not overwrite existing labels in cellpose_segmentation task

### LINKED ISSUE #307: Do not overwrite existing labels when adding a new one
From https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/298#issuecomment-1437979168.

---

> side question: @tcompa how did you load multiple label images at once? The napari-ome-zarr plugin only ever loads the last label image, right?

The reader does load more than one image (https://github.com/ome/ome-zarr-py/blob/master/ome_zarr/reader.py#L191-L197), provided they are all listed in `labels/.zattrs`.
Our current cellpose task is wrong, since it has this block
```python
    labels_group = zarr.group(f"{zarrurl}labels")
    labels_group.attrs["labels"] = [output_label_name]
```
that simply replaces all existing labels with the current one. I'll open a reminder issue right now.
The upcoming task (as well as the napari-workflows one) do have the correct logic, which looks like:
```python
    new_labels = [output_label_name]
    try:
        with open(f"{zarrurl}labels/.zattrs", "r") as f_zattrs:
            existing_labels = json.load(f_zattrs)["labels"]
    except FileNotFoundError:
        existing_labels = []
    intersection = set(new_labels) & set(existing_labels)
    logger.info(f"{new_labels=}")
    logger.info(f"{existing_labels=}")
    if intersection:
        raise RuntimeError(
            f"Labels {intersection} already exist " "but are part of outputs"
        )
    labels_group = zarr.group(f"{zarrurl}labels")
    labels_group.attrs["labels"] = existing_labels + new_labels
```

### PR DESCRIPTION
**Pull request by tcompa**
Close #307

### CODE REVIEW

**Comment by jluethi** [comment]
Ah, nice approach!
Is there still a fix needed for many channels? Cellpose doesn't return more than one channel anyway, right? There is still a comment for `# FIXME deal with: (1) many channels`

**Comment by tcompa** [comment]
> Is there still a fix needed for many channels?

I don't think so.

> Cellpose doesn't return more than one channel anyway, right?

That's correct. The current task takes a single input channel (identified via either `wavelength_id` or `channel_label`) and then has this logic
```python
    # Find channel index
    try:
        channel = get_channel_from_image_zarr(
            image_zarr_path=zarrurl,
            wavelength_id=wavelength_id,
            label=channel_label,
        )
    except ChannelNotFoundError as e:
        logger.warning(
            "Channel not found, exit from the task.\n"
            f"Original error: {str(e)}"
        )
        return {}
    ind_channel = channel["index"]

    # Load ZYX data
    data_zyx = da.from_zarr(f"{zarrurl}{level}")[ind_channel]

    # ...
```

As for the channel name (which is the name of the label folder), this is obtained as in
```python
    # Set channel label - FIXME: adapt to new channels structure
    if output_label_name is None:
        try:
            omero_label = zattrs["omero"]["channels"][ind_channel]["label"]
            output_label_name = f"label_{omero_label}"
        except (KeyError, IndexError):
            output_label_name = f"label_{ind_channel}"
```

I don't see anything obviously wrong, so I'll remove the FIXME (unless you do spot something weird, @jluethi)

**Comment by tcompa** [comment]
> I don't see anything obviously wrong, so I'll remove the FIXME (unless you do spot something weird, @jluethi)

I take it back. Since we already defined a `channel` object, that's where we should get the name from.

**Comment by tcompa** [comment]
Fixed with https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/308/commits/bd2ffbe631ed5f909b9f3f7ff13260a77abd0f78.

@jluethi, this is in principle ready to merge, but I'll wait for comments - just in case

**Comment by jluethi** [comment]
The channel handling part looks good to me.

> As for the channel name (which is the name of the label folder)

This part I don't understand. The output is a label image, which will be in a folder called `output_label_name`. If `output_label_name` is not set, we need to have some default handling, as you posted above and that looks reasonable to me. If that can already be gotten from the `channel` object, even better :)

Side-note: I will look into making cellpose work with dual-channel input. But that's unrelated to this PR and I'll create a new PR. Makes sense to base it on this code though, so I'll wait for this to be merged into main (don't need a release for that, will anyway test running it locally now)

**Comment by jluethi** [comment]
> @jluethi, this is in principle ready to merge, but I'll wait for comments - just in case

LGTM!

**Comment by tcompa** [comment]
The "default" logic is indeed needed, but what was missing was "let's use the channel object, since we already have it" - and that's what the second FIXME was there for.

**Comment by tcompa** [comment]
> I'll wait for this to be merged into main (don't need a release for that, will anyway test running it locally now)

I'll merge right after the CI is complete.

Note, by the way, that you may want to stick with this main for a while (the one after this PR is merged), because right after this one I will merge #303 - and that one will be the beginning of some important changes (not there in #303 yet, but all related to #300).

**Comment by jluethi** [comment]
Sounds good! Then let's actually make this a minor release, so we can refer to e.g. tasks 0.7.3 vs. the upcoming 0.8.x tasks :)

**Comment by tcompa** [comment]
0.7.3 is now on pypi

**Comment by jluethi** [comment]
Thank you @tcompa !

**Pull request merged**
