### PR TITLE
Refactor Yokogawa metadata parsing

### PR DESCRIPTION
**Pull request by jluethi**
https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/109 can be fixed by changing how the comparison of Z steps is made. The prior approach was not stable when the step sizes varied by tiny amounts due to float imprecision.

I deactivated a second check that used the same approach of measuring standard-deviation of values, as this may also have issues with float imprecisions in some edge cases. Not convinced this check is actually necessary and don't know yet how we'd implement this safely, so it's just off for the moment.

### CODE REVIEW

**Comment by tcompa** [comment]
In `lib_remove_FOV_overlaps` we set and use a tolerance threshold of `1e-10 um` to get rid of similar problems when we need fine comparisons of floats. It's non the most elegant solution, but it quickly gets you to the result and it appears quite stable (when will anything be small than 1e-10 um?). It can be decorated with additional safety checks, by comparing the tolerance to other scales (e.g. in `remove_FOV_overlaps` we verify that the tolerance is at least 1000 times smaller than the smallest pixel size).

**Comment by tcompa** [comment]
Small addendum: you are already using a tolerance (via `np.allclose`), and it is actually even more generous than the one I mentioned (defaults for absolute/relative tolerances are `rtol=1e-05, atol=1e-08`). Thus if you'd like to have the second test back, you can just compare a collective quantity (I think averages are better than sums, in that case, to remain stable also for a very large number of elements) with a finite tolerance.

**Comment by jluethi** [comment]
Now added the refactor for https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/94
Will need to clean up (checking for errors in the metadata file, handling those correctly) before this can be merge

**Comment by jluethi** [comment]
This PR refactors the metadata parsing. It achieves 3 things:
1) Significantly simplify the reading of the mlf file by switching to `pandas.read_xml`
2) Significantly speed up reading large mlf files by switching to `pandas.read_xml` (=> closing #94 )
3) Make all the consistency checks robust to float imprecision, thus solving https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/109

I was also looking at https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/110, though it appears that is more linked to actual overlap in the ROIs, which is out-of-scope for the moment.

Switching to `pandas.read_xml` required adding `lxml` to the dependencies. Testing this was a bit tricky on my Mac, because the installation of Fractal tasks dependencies appears to have some issues as the moment on Apple Silicon machines.

I tested the installation on the pelkmans lab cluster using poetry and pip install (separately). Both seem to work and I can import both `fractal_tasks_core` as well as `lxml` afterwards. Thus, I think it's save to merge from the dependency point.

I also successfully tested it with `fractal-server==0.2.1, fractal-client==0.2.4` and this version of the tasks. It still places all the FOVs correctly, thus also functionally works.

=> I'll merge this into main now

**Pull request merged**
