### PR TITLE
Refactor core-library modules

### PR DESCRIPTION
**Pull request by tcompa**
Ref #600

## Checklist before merging
- [x] I added an appropriate entry to `CHANGELOG.md`

### CODE REVIEW

**Comment by tcompa** [comment]
For the record, here is (part of) the current package structure:
```
$ tree -L 2 -I tasks -I dev

.
├── __FRACTAL_MANIFEST__.json
├── __init__.py
├── ome_zarr
│   ├── channels.py
│   ├── __init__.py
│   ├── input_models.py
│   ├── masked_loading.py
│   ├── ngff.py
│   ├── pyramids.py
│   ├── read_fractal_metadata.py
│   ├── write.py
│   └── zattrs_utils.py
├── roi
│   ├── __init__.py
│   ├── load_region.py
│   ├── _overlaps_common.py
│   ├── v1_checks.py
│   ├── v1_overlaps.py
│   └── v1.py
├── tables
│   ├── __init__.py
│   └── v1.py
├── upscale_array.py
└── yokogawa
    ├── filenames.py
    ├── __init__.py
    └── metadata.py

4 directories, 23 files
```

**Comment by tcompa** [comment]
A first bunch of minor issues where I think we can still improve:

- [ ] in `fractal_tasks_core.roi.is_ROI_table_valid`, we validate both the ROI contents and the Zarr attributes --> should we split this into two functions, which belong either to `roi` or to `tables` subpackages?
- [ ] should we rename `fractal_tasks_core.ome_zarr` into `fractal_tasks_core.ngff`? This would be mostly for import-statement length
- [ ] Either way, should the current `fractal_tasks_core.ome_zarr.ngff` module become something like `fractal_tasks_core.ome_zarr.specs` or `fractal_tasks_core.ome_zarr.metadata`? Or, if we take the other option, something like `fractal_tasks_core.ngff.specs` or `fractal_tasks_core.ngff.metadata`?

**Comment by jluethi** [comment]
> should we rename fractal_tasks_core.ome_zarr into fractal_tasks_core.ngff? This would be mostly for import-statement length

I'd make the following separation: Things that validate a json structure are ngff. Things that use the zarr API, e.g. to load zattrs or other zarr specific parts are ome-zarr.

In the (far) future, there might be other ngff backends besides zarr, which was the motivation to keep the specification abstract with its own ngff name

**Comment by tcompa** [comment]
> > should we rename fractal_tasks_core.ome_zarr into fractal_tasks_core.ngff? This would be mostly for import-statement length
> 
> I'd make the following separation: Things that validate a json structure are ngff. Things that use the zarr API, e.g. to load zattrs or other zarr specific parts are ome-zarr.
> 
> In the (far) future, there might be other ngff backends besides zarr, which was the motivation to keep the specification abstract with its own ngff name

I'm going with the following trade-off:
* We do separate the `ngff` and `ome_zarr` subpackages.
* As for the "Zarr vs JSON" separation, I'm keeping it at the module level (`ngff/specs.py` vs `ngff/zarr_utils.py`), but I'm keeping the two modules in the same subpackage so that the `zarr_utils.py` remain close to their main ingredients (as they mostly are thin validation wrappers).
* The day when a new (non-Zarr) NGFF backend appears, we add another `ngff/new_backend_utils.py` file next to `ngff/zarr_utils.py`.
* The day when we want to rely on https://github.com/JaneliaSciComp/pydantic-ome-ngff or a similar library, we will replace the `ngff` submodule with imports from the new library. Note: such new library will most-likely be Zarr-based (for validation across hierarchy levels), and that's why it would replace the whole `ngff` subpackage, and not just `ngff/specs.py`.

**Comment by tcompa** [comment]
Here is the current status. I think things are improving, but we may still clean up the structure a bit, especially in `ome_zarr` subpackage - which is the least well-defined one. I'll now look at the `write.py` location and scope.


```
$ tree -L 2 -I tasks -I dev fractal_tasks_core/ -I __pycache__

fractal_tasks_core/
├── cellvoyager
│   ├── filenames.py
│   ├── __init__.py
│   └── metadata.py
├── __FRACTAL_MANIFEST__.json
├── __init__.py
├── ngff
│   ├── __init__.py
│   ├── specs.py
│   └── zarr_utils.py
├── ome_zarr
│   ├── channels.py
│   ├── __init__.py
│   ├── input_models.py
│   ├── label_group.py
│   ├── masked_loading.py
│   ├── pyramids.py
│   ├── write.py
│   └── zattrs_utils.py
├── roi
│   ├── __init__.py
│   ├── load_region.py
│   ├── _overlaps_common.py
│   ├── v1_checks.py
│   ├── v1_overlaps.py
│   └── v1.py
├── tables
│   ├── __init__.py
│   └── v1.py
└── upscale_array.py
```

**Comment by jluethi** [comment]
Sounds good, great to see this becoming so structured! :)

**Comment by tcompa** [comment]
I think I'm mostly done with this PR, with the structure below. It clearly can still improve, but it's already quite a large refactor.

The last point I'd like to fix is the name of `fractal_tasks_core/write.py`, which is the module where we define:
1. The `OverwriteNotAllowedError` custom error
2. The low-level `open_zarr_group_with_overwrite` function, which wraps `zarr.open_group` by adding overwriting-related checks

Thus this is essentially a wrapper of (a very limited part of) the zarr-python API. This module (which could become a subpackage in the future) should host our own Zarr-related functionalities which are fully unrelated to NGFF or other Fractal-specific features.

I'm tempted to go with `fractal_tasks_core.zarr`. This is against my own advice about the risk of overlap between `from .zarr` and `from zarr`, although I can partly take it back since `from zarr import open_zarr_group_with_overwrite` would always fail (while the correct form could be `from .zarr import open_zarr_group_with_overwrite`, when accessing it from the same folder).

I'll now proceed with this one, and then that's mostly it from me here (cc @jluethi). If there are better suggestions on this name, they are welcome.

---


```
$ tree -L 2 -I tasks -I dev fractal_tasks_core/ -I __pycache__

fractal_tasks_core/
├── cellvoyager
│   ├── filenames.py
│   ├── __init__.py
│   └── metadata.py
├── __FRACTAL_MANIFEST__.json
├── __init__.py
├── labels.py
├── ngff
│   ├── __init__.py
│   ├── specs.py
│   └── zarr_utils.py
├── ome_zarr
│   ├── channels.py
│   ├── __init__.py
│   ├── input_models.py
│   ├── masked_loading.py
│   ├── pyramids.py
│   └── zattrs_utils.py
├── roi
│   ├── __init__.py
│   ├── load_region.py
│   ├── _overlaps_common.py
│   ├── v1_checks.py
│   ├── v1_overlaps.py
│   └── v1.py
├── tables
│   ├── __init__.py
│   └── v1.py
├── upscale_array.py
└── write.py
```

**Comment by jluethi** [comment]
Big fan of how cellvoyager, rois & tables are separate. And generally of the additional structure added.

The 2 questions I'd like to briefly review tomorrow:
- ngff vs. ome-zarr split in functionality
- Do we have a top-level zarr.py and an ome-zarr module? The zarr.py functionality is unrelated to the ome-zarr module?

**Comment by tcompa** [comment]
Latest structure:

```
fractal_tasks_core/
├── cellvoyager
│   ├── filenames.py
│   ├── __init__.py
│   └── metadata.py
├── ngff
│   ├── __init__.py
│   ├── specs.py
│   └── zarr_utils.py
├── roi
│   ├── __init__.py
│   ├── load_region.py
│   ├── _overlaps_common.py
│   ├── v1_checks.py
│   ├── v1_overlaps.py
│   └── v1.py
├── tables
│   ├── __init__.py
│   └── v1.py
├── tasks
│   ├── apply_registration_to_image.py
│   ├── apply_registration_to_ROI_tables.py
│   ├── calculate_registration_image_based.py
│   ├── cellpose_segmentation.py
│   ├── compress_tif.py
│   ├── copy_ome_zarr.py
│   ├── create_ome_zarr_multiplex.py
│   ├── create_ome_zarr.py
│   ├── illumination_correction.py
│   ├── import_ome_zarr.py
│   ├── __init__.py
│   ├── maximum_intensity_projection.py
│   ├── napari_workflows_wrapper_models.py
│   ├── napari_workflows_wrapper.py
│   ├── _utils.py
│   └── yokogawa_to_ome_zarr.py
├── __FRACTAL_MANIFEST__.json
├── __init__.py
├── channels.py
├── labels.py
├── masked_loading.py
├── pyramids.py
├── upscale_array.py
├── utils.py
└── zarr_utils.py
```


Side note: `napari_workflows_wrapper_models.py` is needed (next to `napari_workflows_wrapper.py`) so that this file can be imported (to generate JSON Schemas) without relying on `import napari_workflows` (which may not be available, depending on the presence/absence of the pip extra).

**Comment by tcompa** [comment]
Here is a first version of the main `import` changes; note that I only tracked the one from within `fractal_tasks_core/tasks`.

I sorted them by original import, and I will now group them a bit to make it more readable (and then put this info somewhere in the docs).



```diff
-from fractal_tasks_core.lib_channels import ChannelNotFoundError
+from fractal_tasks_core.channels import ChannelNotFoundError

-from fractal_tasks_core.lib_channels import OmeroChannel
+from fractal_tasks_core.channels import OmeroChannel

-from fractal_tasks_core.lib_channels import check_unique_wavelength_ids
+from fractal_tasks_core.channels import check_unique_wavelength_ids

-from fractal_tasks_core.lib_channels import check_well_channel_labels
+from fractal_tasks_core.channels import check_well_channel_labels

-from fractal_tasks_core.lib_channels import define_omero_channels
+from fractal_tasks_core.channels import define_omero_channels

-from fractal_tasks_core.lib_channels import get_channel_from_image_zarr
+from fractal_tasks_core.channels import get_channel_from_image_zarr

-from fractal_tasks_core.lib_channels import get_omero_channel_list
+from fractal_tasks_core.channels import get_omero_channel_list

-from fractal_tasks_core.lib_channels import update_omero_channels
+from fractal_tasks_core.channels import update_omero_channels

-from fractal_tasks_core.lib_glob import glob_with_multiple_patterns
+from fractal_tasks_core.cellvoyager.filenames import glob_with_multiple_patterns

-from fractal_tasks_core.lib_input_models import Channel
+from fractal_tasks_core.channels import ChannelInputModel

-from fractal_tasks_core.lib_input_models import NapariWorkflowsInput
+from fractal_tasks_core.tasks.napari_workflows_wrapper_models import NapariWorkflowsInput

-from fractal_tasks_core.lib_input_models import NapariWorkflowsOutput
+from fractal_tasks_core.tasks.napari_workflows_wrapper_models import NapariWorkflowsOutput

-from fractal_tasks_core.lib_masked_loading import masked_loading_wrapper
+from fractal_tasks_core.masked_loading import masked_loading_wrapper

-from fractal_tasks_core.lib_metadata_parsing import parse_yokogawa_metadata
+from fractal_tasks_core.cellvoyager.metadata import parse_yokogawa_metadata

-from fractal_tasks_core.lib_ngff import NgffImageMeta
+from fractal_tasks_core.ngff import NgffImageMeta

-from fractal_tasks_core.lib_ngff import detect_ome_ngff_type
+from fractal_tasks_core.ngff import detect_ome_ngff_type

-from fractal_tasks_core.lib_ngff import load_NgffImageMeta
+from fractal_tasks_core.ngff import load_NgffImageMeta

-from fractal_tasks_core.lib_ngff import load_NgffWellMeta
+from fractal_tasks_core.ngff import load_NgffWellMeta

-from fractal_tasks_core.lib_parse_filename_metadata import parse_filename
+from fractal_tasks_core.cellvoyager.filenames import parse_filename

-from fractal_tasks_core.lib_pyramid_creation import build_pyramid
+from fractal_tasks_core.pyramids import build_pyramid

-from fractal_tasks_core.lib_read_fractal_metadata import get_parameters_from_metadata
+from fractal_tasks_core.utils import get_parameters_from_metadata

-from fractal_tasks_core.lib_regions_of_interest import are_ROI_table_columns_valid
+from fractal_tasks_core.roi import are_ROI_table_columns_valid

-from fractal_tasks_core.lib_regions_of_interest import array_to_bounding_box_table
+from fractal_tasks_core.roi import array_to_bounding_box_table

-from fractal_tasks_core.lib_regions_of_interest import check_valid_ROI_indices
+from fractal_tasks_core.roi import check_valid_ROI_indices

-from fractal_tasks_core.lib_regions_of_interest import convert_ROI_table_to_indices
+from fractal_tasks_core.roi import convert_ROI_table_to_indices

-from fractal_tasks_core.lib_regions_of_interest import convert_ROIs_from_3D_to_2D
+from fractal_tasks_core.roi import convert_ROIs_from_3D_to_2D

-from fractal_tasks_core.lib_regions_of_interest import convert_indices_to_regions
+from fractal_tasks_core.roi import convert_indices_to_regions

-from fractal_tasks_core.lib_regions_of_interest import empty_bounding_box_table
+from fractal_tasks_core.roi import empty_bounding_box_table

-from fractal_tasks_core.lib_regions_of_interest import find_overlaps_in_ROI_indices
+from fractal_tasks_core.roi import find_overlaps_in_ROI_indices

-from fractal_tasks_core.lib_regions_of_interest import get_image_grid_ROIs
+from fractal_tasks_core.roi import get_image_grid_ROIs

-from fractal_tasks_core.lib_regions_of_interest import get_overlapping_pairs_3D
+from fractal_tasks_core.roi import get_overlapping_pairs_3D

-from fractal_tasks_core.lib_regions_of_interest import get_single_image_ROI
+from fractal_tasks_core.roi import get_single_image_ROI

-from fractal_tasks_core.lib_regions_of_interest import is_ROI_table_valid
+from fractal_tasks_core.roi import is_ROI_table_valid

-from fractal_tasks_core.lib_regions_of_interest import is_standard_roi_table
+from fractal_tasks_core.roi import is_standard_roi_table

-from fractal_tasks_core.lib_regions_of_interest import load_region
+from fractal_tasks_core.roi import load_region

-from fractal_tasks_core.lib_regions_of_interest import prepare_FOV_ROI_table
+from fractal_tasks_core.roi import prepare_FOV_ROI_table

-from fractal_tasks_core.lib_regions_of_interest import prepare_well_ROI_table
+from fractal_tasks_core.roi import prepare_well_ROI_table

-from fractal_tasks_core.lib_regions_of_interest import remove_FOV_overlaps
+from fractal_tasks_core.roi import remove_FOV_overlaps

-from fractal_tasks_core.lib_tables import write_table
+from fractal_tasks_core.tables import write_table

-from fractal_tasks_core.lib_upscale_array import upscale_array
+from fractal_tasks_core.upscale_array import upscale_array

-from fractal_tasks_core.lib_write import OverwriteNotAllowedError
+from fractal_tasks_core.zarr_utils import OverwriteNotAllowedError

-from fractal_tasks_core.lib_write import open_zarr_group_with_overwrite
+from fractal_tasks_core.zarr_utils import open_zarr_group_with_overwrite

-from fractal_tasks_core.lib_write import prepare_label_group
+from fractal_tasks_core.labels import prepare_label_group

-from fractal_tasks_core.lib_zattrs_utils import get_table_path_dict
+from fractal_tasks_core.utils import get_table_path_dict

-from fractal_tasks_core.lib_zattrs_utils import rescale_datasets
+from fractal_tasks_core.utils import rescale_datasets
```

**Comment by tcompa** [comment]
I'm merging this one, and I'll give it a final review before releasing 0.14.0.

**Comment by jluethi** [comment]
Awesome, great that we have this core library refactor now!

**Pull request merged**
