### PR TITLE
Fix multiplexing expected channel parsing & support for empty ROI table output for cellpose

### PR DESCRIPTION
**Pull request by jluethi**
This fixes https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/285 by making the check for actual wavelengths acquisition-specific.

### CODE REVIEW

**Comment by jluethi** [comment]
I also added support a fix for https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/354 (to this branch by mistake). Now this PR is also closing that bug.

The new way of handling empty ROI table outputs is to still write a ROI table, just an empty one. I'm adding an example workflow to example 06 that actually runs it that way.
The cellpose task can already handle processing an empty ROI table, it just creates an empty output label image of the correct dimensions.
The napari-ome-zarr task had an issue in the output handling, now there's a check that writes an empty AnnData table if now measurements were made (because the ROI table was empty).

**Comment by jluethi** [comment]
See here for the empty cellpose output example: https://github.com/fractal-analytics-platform/fractal-demos/pull/47

**Comment by jluethi** [comment]
This PR is ready for review from my side @tcompa 

Would be great if you could have a look and include this in the next task release, e.g. 0.9.3.

**Comment by tcompa** [comment]
> The cellpose task can already handle processing an empty ROI table, it just creates an empty output label image of the correct dimensions.

Let me see if I understand correctly:

The cellpose task was already correct (and indeed it is not modified by this PR), in these parts
```python
        if output_ROI_table:

            bbox_df = array_to_bounding_box_table(
                new_label_img, actual_res_pxl_sizes_zyx
            )

            bbox_dataframe_list.append(bbox_df)

            overlap_list = []
            for df in bbox_dataframe_list:
                overlap_list.extend(
                    get_overlapping_pairs_3D(df, full_res_pxl_sizes_zyx)
                )
            if len(overlap_list) > 0:
                logger.warning(
                    f"{len(overlap_list)} bounding-box pairs overlap"
                )
...
    if output_ROI_table:
        # Concatenate all ROI dataframes
        df_well = pd.concat(bbox_dataframe_list, axis=0, ignore_index=True)
        df_well.index = df_well.index.astype(str)
        # Extract labels and drop them from df_well
        labels = pd.DataFrame(df_well["label"].astype(str))
        df_well.drop(labels=["label"], axis=1, inplace=True)
        # Convert all to float (warning: some would be int, in principle)
        bbox_dtype = np.float32
        df_well = df_well.astype(bbox_dtype)
        # Convert to anndata
        bbox_table = ad.AnnData(df_well, dtype=bbox_dtype)
        bbox_table.obs = labels
        # Write to zarr group
        group_tables = zarr.group(f"{in_path}/{component}/tables/")
        write_elem(group_tables, output_ROI_table, bbox_table)
        logger.info(
            "Bounding box ROI table written to "
            f"{in_path}/{component}/tables/{output_ROI_table}"
        )
```

The issue in #354 was rather due to the `array_to_bounding_box_table` failing when passed an all-zeros `mask_array` (now fixed with this PR).

Did I get it right?

**Comment by jluethi** [comment]
Yes, the cellpose task failed to write a ROI table when the content of the ROI table was empty (no label objects in that well). But those fixes were in the lib functions in `lib_regions_of_interest.py`. Once that was fixed, the cellpose task then just wrote empty ROI tables if no objects were detected in a well => fulfilling the desired behavior.

The secondary question then was whether these empty ROI tables can be used as input to our tasks. For the cellpose task, that already works. The napari workflow task needed another minor fix to support this.

**Comment by jluethi** [comment]
I added a small extra fix to the napari workflows task to avoid getting the `ImplicitModificationWarning`s in the AnnData conversion of the ROI table that I just stumbled across in some other task work for the scMultipleX task.

**Comment by tcompa** [comment]
I reviewed the part related to #354, and added tests for cellpose/napari tasks running with an empty ROI table as input (as well as a couple of trivial unit tests for ROI functions).

I still need to go through the multiplexing part.

**Comment by jluethi** [comment]
Nice, thanks a lot @tcompa !

The multiplexing part is simpler. Before, it used the channels of the last acquisition to check whether the correct channels are present in each acquisition (I don't think that was intentional). Now, it stores the actual channels in the `dict_acquisitions` and uses that during the checks => checks whether the expected channels for a given acquisition are present.

**Comment by jluethi** [comment]
Looks all good to me, thanks for adding the tests! Can you do the 0.9.3 release?

**Comment by tcompa** [comment]
> Can you do the 0.9.3 release?

Done

**Pull request merged**
