### PR TITLE
Improve handling of pydantic models upon creating args schemas

### PR DESCRIPTION
**Pull request by tcompa**
ref #444

### CODE REVIEW

**Comment by tcompa** [comment]
The only relevant change is in `fractal_tasks_core/dev/lib_args_schemas.py`, but I also prepared a folder `tests/data/fake_package_for_schema_experiments/` with an example of how `new_args_schema.py` would look like for a different package.

For the moment I did not include any additional custom models, but I can try now to check that it works.

**Review by jluethi — APPROVED** [review]
Looks good to me, nice combination of core models + user models!

**Comment by tcompa** [comment]
> For the moment I did not include any additional custom models, but I can try now to check that it works.

Done.

The example for `new_args_schema` looks like
```python
...
    # Loop over tasks and set args schemas
    task_list = manifest["task_list"]
    for ind, task in enumerate(task_list):
        executable = task["executable"]
        print(f"[{executable}] Start")
        try:
            schema = create_schema_for_single_task(
                executable,
                package="my_package",
                custom_pydantic_models=[
                    ("my_package", "lib_custom_models.py", "CustomModel")
                ],
            )
        except Exception as e:
            print(f"[{executable}] Skip. Original error:\n{str(e)}")

        manifest["task_list"][ind]["args_schema"] = schema
        print("Schema added to manifest")
        print()
...
```
and the manifest looks like
```json
{
  "task_list": [
    {
      "name": "Task Name",
      "executable": "tasks/my_task.py",
      "args_schema": {
        "title": "MyTask",
        "type": "object",
        "properties": {
          "x": {
            "title": "X",
            "type": "integer",
            "description": "Missing description"
          },
          "y": {
            "$ref": "#/definitions/OmeroChannel",
            "description": "Missing description"
          },
          "z": {
            "$ref": "#/definitions/CustomModel",
            "description": "Missing description"
          }
        },
        "required": [
          "x",
          "y",
          "z"
        ],
        "additionalProperties": false,
        "definitions": {
          "Window": {
            "title": "Window",
            "description": "Custom class for Omero-channel window, based on OME-NGFF v0.4.",
            "type": "object",
            "properties": {
              "min": {
                "title": "Min",
                "type": "integer",
                "description": "Do not change. It will be set to ``0`` by default."
              },
              "max": {
                "title": "Max",
                "type": "integer",
                "description": "Do not change. It will be set according to bit-depth of the images by default (e.g. 65535 for 16 bit images)."
              },
              "start": {
                "title": "Start",
                "type": "integer",
                "description": "Lower-bound rescaling value for visualization."
              },
              "end": {
                "title": "End",
                "type": "integer",
                "description": "Upper-bound rescaling value for visualization."
              }
            },
            "required": [
              "start",
              "end"
            ]
          },
          "OmeroChannel": {
            "title": "OmeroChannel",
            "description": "Custom class for Omero channels, based on OME-NGFF v0.4.",
            "type": "object",
            "properties": {
              "wavelength_id": {
                "title": "Wavelength Id",
                "type": "string",
                "description": "Unique ID for the channel wavelength, e.g. ``A01_C01``."
              },
              "index": {
                "title": "Index",
                "type": "integer",
                "description": "Do not change. For internal use only."
              },
              "label": {
                "title": "Label",
                "type": "string",
                "description": "Name of the channel"
              },
              "window": {
                "$ref": "#/definitions/Window",
                "description": "Optional ``Window`` object to set default display settings for napari."
              },
              "color": {
                "title": "Color",
                "type": "string",
                "description": "Optional hex colormap to display the channel in napari (e.g. ``00FFFF``)."
              },
              "active": {
                "title": "Active",
                "default": true,
                "type": "boolean",
                "description": "Should this channel be shown in the viewer?"
              },
              "coefficient": {
                "title": "Coefficient",
                "default": 1,
                "type": "integer",
                "description": "Do not change. Omero-channel attribute. "
              },
              "inverted": {
                "title": "Inverted",
                "default": false,
                "type": "boolean",
                "description": "Do not change. Omero-channel attribute."
              }
            },
            "required": [
              "wavelength_id"
            ]
          },
          "CustomModel": {
            "title": "CustomModel",
            "type": "object",
            "properties": {
              "x": {
                "title": "X",
                "type": "integer",
                "description": "Missing description"
              }
            },
            "required": [
              "x"
            ]
          }
        }
      }
    }
  ],
  "has_args_schemas": true,
  "args_schema_version": "pydantic_v1"
}
```

**Comment by jluethi** [comment]
Great, thanks @tcompa !

**Pull request merged**
